package pl.sii.javaBeginers.doublecolon.mykong3;

import java.math.BigDecimal;

class Invoice1 {

    String no;
    BigDecimal unitPrice;
    Integer qty;

    public Invoice1() {
    }

    public Invoice1(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Invoice1(String no, BigDecimal unitPrice, Integer qty) {
        this.no = no;
        this.unitPrice = unitPrice;
        this.qty = qty;
    }

    public String getNo() {
        return no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Integer getQty() {
        return qty;
    }

    public void setQty(Integer qty) {
        this.qty = qty;
    }

    @Override
    public String toString() {
        return "Invoice{" +
                "no='" + no + '\'' +
                ", unitPrice=" + unitPrice +
                ", qty=" + qty +
                '}';
    }

    // generated by IDE, setters, gettes, constructor, toString
}