<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>pl.sii</groupId>
    <artifactId>selenumBasic</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <!-- 1. WŁAŚCIWOŚCI PROJEKTU I KOMPILACJI (Język i Kodowanie) -->
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- 2. WERSJE PLUGINÓW MAVENA -->
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
        <maven.surefire.plugin.version>3.3.1</maven.surefire.plugin.version>

        <!-- 3. WERSJE ZALEŻNOŚCI (Biblioteki) -->
        <cucumber.version>7.29.0</cucumber.version>
        <junit.platform.version>1.13.4</junit.platform.version>
        <junit.jupiter.version>5.10.2</junit.jupiter.version>
        <lombok.version>1.18.42</lombok.version>
        <jna.version>5.14.0</jna.version>
        <commons-collections4.version>4.5.0</commons-collections4.version>
        <commons.lang3.version>3.19.0</commons.lang3.version>
        <jackson.databind.verion>2.17.1</jackson.databind.verion>
        <cucumber-picocontainer.version>7.29.0</cucumber-picocontainer.version>
        <json-path.version>2.9.0</json-path.version>

        <tagi.grupa1>@TablesType1</tagi.grupa1>
        <tagi.grupa2>@TablesType2</tagi.grupa2>
        <tagi.grupa3>@TablesType3</tagi.grupa3>
        <tagi.wszystkie>${tagi.grupa1} or ${tagi.grupa2} or ${tagi.grupa3}</tagi.wszystkie>
        <tags.to.run>${tagi.wszystkie}</tags.to.run>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine
            </artifactId><!-- tu zmiana cucumber-junit na cucumber-junit-platform-engine -->
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <version>${junit.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>${junit.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- WYMUSZENIE WERSJI: Dodajemy Commons, aby upewnić się, że klasa
             'org.junit.platform.commons.support.Resource' jest dostępna w wersji 1.10.2. -->
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-commons</artifactId>
            <version>${junit.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>${jna.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>${jna.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>${commons-collections4.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons.lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.databind.verion}
            </version> <!-- Sprawdź, czy wersja odpowiada tej w Pana properties, jeśli istnieje -->
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>${cucumber-picocontainer.version}</version>
            <scope>test</scope>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>junit</groupId>-->
        <!--            <artifactId>junit</artifactId>-->
        <!--            <version>4.13.2</version>-->
        <!--            <scope>test</scope>-->
        <!--        </dependency>-->
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>${json-path.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <!-- Jawne ustawienie procesora adnotacji dla Lomba -->
                    <release>${java.version}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <includes>
<!--                        <include>**/RunCucumberTest.java</include>-->
                    </includes>
                    <systemPropertyVariables>
                        <junit.platform.reporting.details.enable>false</junit.platform.reporting.details.enable>
                        <junit.platform.log.capture.enabled>false</junit.platform.log.capture.enabled>
                        <cucumber.filter.tags>${tags.to.run}</cucumber.filter.tags>
                    </systemPropertyVariables>
                    <!--                    <properties>-->
                    <!--                        <property>-->
                    <!--                            <name>cucumber.filter.tags</name>-->
                    <!--                            <value>${tag.selection}</value>-->
                    <!--                        </property>-->
                    <!--                    </properties>-->
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>